#cloud-config
package_update: true
package_upgrade: false

users:
  - default
  - name: kyle
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCyR0gm9rwbipcfd7Aq4/K+DUAtkjDgJIdMu7bOyZ7rM3qNtrHR1fEmuOe7n0dqwwjSN9OmgaPfurMClyPTMhKlbl3Zve5JSQLoDAlfIhHH/zPSuetOfWpXW1bpUFdiZz1tEiK/6Hr0ZiQnQvYDcWIU5B8+jeHy9us9io3HEpodaX5UDb4Xard0fYIKn9sUAzX38AqAp++B+im0eHecPgBGDYQgUhQpobq09n9eBnIgAO0wySgnVK4hqSfNvHU1D+nl5OzmrsAFE1byPzb3E3Kks/xrBEkxduKrtX6xXjj72852wbdLIHApEL7FXGfPSNgN45yPseNpidPoY+i4KJ7FAI0wgc2GdSxe8T1FQRbYexuLWEL3l9dHHEY1Cy4LDe3763iHGBOELtVos78/i8MgHm5UDU2BDCwEqNNpm3mO8VekYU1lmDBNwqZq/qHAo1y3EfVsnPl1O2Y9eg07d/hKpQmgr/J5rvhg5JLWebWMVakTNHauwTXM5USZky7AEZs= kmeier@desc-23
