#cloud-config
package_update: true
package_upgrade: false

users:
  - default
  - name: said
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCI2GQbr8KG9eoqzm1z4Rr2m3luJ6s/4EPKsRd+8DOVH7Id4STgxhT8TfAuuqMWeK59HVHpTO2Cwz9HrT0nWbxR1dme4JUxqO6McIt2RvSIoko36E2zfmflF+ojHcn1pZbncz2k69SUEDX9Uj/5xu0ysvDwoVOaKDTcPAuo9pjJ4lBsel88Q2jgNTNq+rF0gI4/uWkuOGokZUPgPj8nNp+yhiXO04Cfkr0fsKenv5S/9v3RymR7QZGdkpIBu3m1uoLuqzyHv8P1IPXRq+6sCIe7SuJu17SXbvlFCfGp6l9AUEqjZFB4S00JVw5TovibC+nEwiUuo/wQ1gOW/icn/whwG38htEeWm7wnhou4vU6QxYKKCmFIvrwDyr2TTWBffeauGSF0lidRpH5lkdHX6iJ0GHqWx3nTEWmFsQWALyODm2dR/VsjMHwbTLySlkv/w4OifWiJSyFtgtXGj/EydyXuRcD1i4lQwqzrEixCoHKjQJFwlRZo2MRIxg5AqWnw5es= saidsim@SaidComp
